# Generated by Django 5.0.6 on 2024-05-29 15:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webportal',
            fields=[
                ('page_title', models.CharField(max_length=128)),
                ('page_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Newsheadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.UUIDField(default=uuid.uuid4)),
                ('news_title', models.CharField(max_length=512)),
                ('news_upload_date', models.DateField()),
                ('news_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrappingtool.webportal')),
            ],
        ),
    ]
