# Generated by Django 5.0.6 on 2024-06-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappingtool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsheadline',
            name='news_upload_date',
            field=models.TextField(),
        ),
    ]
