# Generated by Django 5.0.6 on 2024-06-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrappingtool', '0002_alter_newsheadline_news_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsheadline',
            name='news_id',
        ),
    ]
