# Generated by Django 5.0.6 on 2024-06-21 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappingtool', '0003_remove_newsheadline_news_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_date', models.DateField(auto_now_add=True)),
                ('featured_news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scrappingtool.newsheadline')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
